trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - DryWetMidi.Benchmarks
    - Docs
    - README.md
    - Resources/CI/benchmarks-develop-win.yaml
    - Resources/CI/build-artifacts-library.yaml
    - Resources/CI/build-artifacts-docs.yaml
    - Resources/CI/check-readme-links.yaml
    - .github/**/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '5.1.0'

name: $(TeamProject)_$(SourceBranchName)_BuildAndTest_Windows_$(version)$(Rev:.r)

steps:
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: PowerShell@2
  displayName: Setup MIDI ports for devices API tests
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Setup MIDI ports.ps1'

- task: DotNetCoreCLI@2
  displayName: "Publish tests assemblies"
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.Tests.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory) -f netcoreapp2.1'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: test
    projects: '$(Build.ArtifactStagingDirectory)/**/*.Tests.dll'
    arguments: '--configuration $(buildConfiguration) --list-tests -v d'